# Generated by Django 5.0.6 on 2026-09-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('cool', 'Cool'), ('warm', 'Warm')], default='medium', max_length=10),
        ),
    ]
