# Generated by Django 5.0.6 on 2026-09-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_spice_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg'), ('sweet', 'Sweet')], default='veg', max_length=10),
        ),
    ]
